# Generated by Django 6.0.3 on 2026-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(blank=True, default='Xem thêm', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Ví dụ: /tin-tuc/ hoặc https://...', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner trang chủ',
                'verbose_name_plural': 'Banner trang chủ',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Ví dụ: /tai-lieu/ hoặc link ngoài', max_length=255)),
                ('published_at', models.DateField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Thông báo nổi bật',
                'verbose_name_plural': 'Thông báo nổi bật',
                'ordering': ['-is_pinned', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Liên kết nhanh',
                'verbose_name_plural': 'Liên kết nhanh',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_note',
            field=models.CharField(blank=True, help_text='Ví dụ: Giấy phép số..., cơ quan chủ quản...', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Dán link Google Maps Embed để hiển thị bản đồ ở chân trang'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portal_name',
            field=models.CharField(default='Cổng thông tin điện tử', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Cập nhật thông tin chỉ đạo điều hành, tin tức chuyên ngành, tài liệu công bố và các đầu mối liên hệ phục vụ công tác quản lý nhà nước, chuyên môn và truyền thông.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Cổng thông tin điện tử tài nguyên nước', max_length=255),
        ),
    ]
