# Generated by Django 6.0.3 on 2026-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bannerslide_notice_quicklink_document_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=120)),
                ('unit_type', models.CharField(default='Phòng chuyên môn', max_length=120)),
                ('scope', models.CharField(blank=True, help_text='Ví dụ: Miền Bắc, toàn quốc...', max_length=255)),
                ('duties_summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Phòng/Bộ phận',
                'verbose_name_plural': 'Phòng/Bộ phận',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='leadershipmember',
            options={'ordering': ['order', 'full_name'], 'verbose_name': 'Lãnh đạo/nhân sự', 'verbose_name_plural': 'Lãnh đạo/nhân sự'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ministry_name',
            field=models.CharField(default='Bộ Nông nghiệp và Môi trường', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='parent_unit',
            field=models.CharField(default='Trung tâm Quy hoạch và Điều tra tài nguyên nước quốc gia', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_note',
            field=models.CharField(blank=True, help_text='Ví dụ: Cơ quan chủ quản, ghi chú chân trang...', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Cập nhật thông tin chỉ đạo điều hành, tin tức chuyên ngành, tài liệu công bố, chương trình công tác và đầu mối liên hệ phục vụ hoạt động cảnh báo, dự báo tài nguyên nước.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Cổng thông tin điện tử Trung tâm Cảnh báo và Dự báo tài nguyên nước', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_name',
            field=models.CharField(default='CB&DB TNN', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='unit_name',
            field=models.CharField(default='Trung tâm Cảnh báo và Dự báo tài nguyên nước', max_length=255),
        ),
    ]
